<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtalaRepository extends EntityRepository
{
   public function getAtalakByOrdenantzaId($ordenantzaid) {
      $qb = $this->createQueryBuilder('a')
         ->innerJoin('a.ordenantza', 'o', 'WITH', 'o.id = :ordenantzaid')
         ->setParameter('ordenantzaid', $ordenantzaid)
         ->andWhere('((a.ezabatu IS NULL) or (a.ezabatu <> 1))');
      $atalak = $qb->getQuery()->getResult();
      return $atalak;
  }
}
