<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AzpiAtalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AzpiatalaRepository extends EntityRepository
{

   public function getAzpiatalaByUdalaId($udalaId) {
   //    $query = $em->createQuery(
   //       /* @lang text */
   //       'SELECT p.id, p.kodea_prod, p.izenburuaeu_prod, p.izenburuaes_prod 
   //           FROM App:Azpiatala p 
   //           WHERE p.udala=:udalaid AND ((p.ezabatu IS NULL) or (p.ezabatu <> 1))
   //           '
   //   );
   
      $qb = $this->createQueryBuilder('a')
         ->select('a.id,a.kodea_prod,a.izenburuaeu_prod,a.izenburuaes_prod')
         ->innerJoin('a.udala', 'u', 'WITH', 'u.id = :udalaId')
         ->setParameter('udalaId', $udalaId)
         ->andWhere('((a.ezabatu IS NULL) or (a.ezabatu <> 1))');
      $azpiAtalak = $qb->getQuery()->getResult();
      return $azpiAtalak;
  }

//   $query = $em->createQuery( /* @lang text */
//    '
//        SELECT p.id, p.kodea_prod, p.izenburuaeu_prod,p.izenburuaes_prod  
//            FROM App:Azpiatala p 
//        WHERE p.atala=:atalaid AND ((p.ezabatu IS NULL) or (p.ezabatu <> 1))
//  ');
// $query->setParameter('atalaid', $tributuaid);
// $azpiatalak = $query->getResult();

  public function getAzpiatalaByAtalaId($atalaId){
         $qb = $this->createQueryBuilder('a')
            ->select('a.id,a.kodea_prod,a.izenburuaeu_prod,a.izenburuaes_prod')
            ->innerJoin('a.atala', 'at', 'WITH', 'at.id = :atalaId')
            ->setParameter('atalaId', $atalaId)
            ->andWhere('((a.ezabatu IS NULL) or (a.ezabatu <> 1))');
      $azpiAtalak = $qb->getQuery()->getResult();
      return $azpiAtalak;
  }

}
