<?php

namespace App\Repository;

use App\Entity\Udala;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * OrdenantzaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrdenantzaRepository extends EntityRepository
{
    public function getOrdenantzabat($id)
    {
        $em = $this->getEntityManager();


        $dql = "
            SELECT o,p,a,ap,az,azp,k,m,b
                FROM App:Ordenantza o
                    LEFT JOIN o.parrafoak p
                    LEFT JOIN o.atalak a
                    LEFT JOIN a.parrafoak ap
                    LEFT JOIN a.azpiatalak az
                    LEFT JOIN az.parrafoak azp
                    LEFT JOIN az.kontzeptuak k
                    LEFT JOIN k.kontzeptumota m
                    LEFT JOIN k.baldintza b
                WHERE o.id = :id
        ";

//        $qb = $this->createQueryBuilder('o')
//            ->select('o,p,a')
//            ->innerJoin('o.parrafoak','p')
//            ->innerJoin('o.atalak','a')
//            ->leftJoin('a.parrafoak','ap')
//            ->where('o =:id')->setParameter('id', $id)
//            ->where('a =:id')->setParameter('id', $id)
//            ->getQuery()
//            ->getResult(Query::HYDRATE_ARRAY);

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('id', $id);
//        print_r($consulta->getSQL());
        return $consulta->getResult(Query::HYDRATE_ARRAY);

//        return $qb;
    }

    public function getOrdenantzakByUdalKodea(string $kodea) {
        $qb = $this->createQueryBuilder('o')
            ->innerJoin('App:Udala','u')
            ->andWhere('u.kodea = :udalkodea')
            ->setParameter('udalkodea',$kodea)
            ->andWhere('((o.ezabatu IS NULL) or (o.ezabatu <> 1))');

        // $query = $em->createQuery( /* @lang text */
        //     '
        //     SELECT o 
        //     FROM App:Ordenantza o
        //        INNER JOIN App:Udala u
        //     WHERE  AND ((o.ezabatu IS NULL) or (o.ezabatu <> 1))
	    // ORDER BY o.kodea
        //     ');
        // $query->setParameter('udalkodea', $kodea);
        $ordenantzak = $qb->getQuery()->getResult();
        return $ordenantzak;
    }

    // public function getAtalakByOrdenantzaId($ordenantzaid) {
    //     $qb = $this->createQueryBuilder('a')
    //         ->innerJoin('App:Ordenantza','o')
    //         ->andWhere('o.id = :ordenantzaid')
    //         ->andWhere('((a.ezabatu IS NULL) or (a.ezabatu <> 1))');
    //     $qb->setParameter('ordenantzaid', $ordenantzaid);
    //     $atalak = $qb->getQuery()->getResult();
    //     return $atalak;
    // }


}
