# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: eu
    database_host: 127.0.0.1
    database_port: null
    database_name: zzoo
    database_user: zzoo
    database_password: 7GGcUkzJwHbF5M96
    mailer_transport: smtp
    mailer_host: 192.168.18.16
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    alias: /zzoo
    doc_path: doc
    azterketa_azpiatala: 62

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,UserBundle}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # UserBundle\:
    #     resource: '../src/UserBundle'

    # UserBundle\Controller\:
    #     resource: '../src/UserBundle/Controller'
    #     tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.doctrine.filter.configurator:
        class: App\Filter\Configurator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@annotation_reader"
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    easycorp.easylog.handler:
            class: EasyCorp\EasyLog\EasyLogHandler
            arguments:
                - '%kernel.logs_dir%/%kernel.environment%.log'

    # twig.extension.text:
    #     class: Twig_Extensions_Extension_Text
    #     tags:
    #         - { name: twig.extension }